cargo-features = ["profile-rustflags"]

[package]
name = "phrase_search"
version = "0.1.0"
edition = "2021"

[dependencies]
heed = "0.20.5"
unicode-segmentation = "1.12.0"
fxhash = "0.2.1"
ahash = "0.8.11"
rayon = "1.10.0"
clap = { version = "4.5.17", features = ["derive"] }
arbitrary = { version = "1.3.2", features = ["derive"] }
rkyv = { version = "0.8.8", features = ["unaligned"] }

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "roaringish"
harness = false

[profile.release]
debug = true
codegen-units = 1
lto = "fat"
panic = "abort"
incremental = false
rustflags = [
    "-C", "target-cpu=native", 
    "-Z", "tune-cpu=native",
    # "-C", "target-feature=-avx512f",
    # "-C", "target-feature=-avx512vp2intersect",
]