cargo-features = ["profile-rustflags"]


[package]
name = "phrase_search"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.120"
heed = "0.20.3"
roaring = { version = "0.10.6", features = ["serde"] }
unicode-segmentation = "1.11.0"
fxhash = "0.2.1"
ahash = "0.8.11"
rayon = "1.10.0"
bincode = "1.3.3"
clap = { version = "4.5.9", features = ["derive"] }

[profile.release]
debug = true
codegen-units = 1
lto = "fat"
panic = "abort"
incremental = false
rustflags = ["-C", "target-cpu=native", "-Z", "tune-cpu=native"]